# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_ABROLHOS)		+= abrolhos.o
ccflags-y			+= -DCONFIG_EDGETPU_TELEMETRY_TRACE=1
ccflags-y			+= -I$(srctree)/$(src)/include

GIT_PATH=$(srctree)/$(src)
ifeq ($(shell git -C $(GIT_PATH) rev-parse --is-inside-work-tree),true)
	GIT_REPO_STATE=$(shell (git -C $(GIT_PATH) status --porcelain | grep -q .) && echo -dirty)
	ccflags-y	+= -DGIT_REPO_TAG=\"$(shell git -C $(GIT_PATH) rev-parse --short HEAD)$(GIT_REPO_STATE)\"
else
	ccflags-y	+= -DGIT_REPO_TAG=\"Not\ a\ git\ repository\"
endif

edgetpu-objs	:= edgetpu-async.o edgetpu-dmabuf.o edgetpu-iremap-pool.o \
		   edgetpu-kci.o edgetpu-mailbox.o edgetpu-mapping.o \
		   edgetpu-sw-watchdog.o edgetpu-telemetry.o \
		   edgetpu-firmware-util.o edgetpu-firmware.o

abrolhos-objs	:= abrolhos-core.o abrolhos-debug-dump.o \
		   abrolhos-device-group.o abrolhos-fs.o abrolhos-device.o \
		   abrolhos-firmware.o abrolhos-iommu.o \
		   abrolhos-platform.o abrolhos-pm.o abrolhos-thermal.o \
		   abrolhos-usage-stats.o abrolhos-wakelock.o \
		   $(edgetpu-objs)

CFLAGS_abrolhos-fs.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-core.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-device.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-device-group.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-firmware.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-iommu.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-platform.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-pm.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-thermal.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-debug-dump.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-usage-stats.o := -DCONFIG_ABROLHOS=1
CFLAGS_abrolhos-wakelock.o := -DCONFIG_ABROLHOS=1
